### ISSUE TITLE
Unable to parse SAT-SUN range

### ISSUE THREAD

**Issue by rockgecko-development** [karbunkul/dart_easy_cron#1]
Hi, thanks for the simple library!
Unfortunately, when trying to parse a cron expression with a SAT-SUN range, it throws an assertion error. For example:
`UnixCronParser().parse("0 22 * * SAT-SUN")`
throws
`Failed assertion: line 160 pos 12: 'lower < higher && lower >= min && higher <= max': is not true.`

Here's a few unit tests which all currently fail
```dart
 expect(
      next('0 22 * * SAT-SUN', startAt: "2022-11-24 16:00"),
      equals('2022-11-26 22:00'),
    );
    expect(
      next('0 22 * * 6-7', startAt: "2022-11-26 23:00"),
      equals('2022-11-27 22:00'),
    );
    expect(
      schedule('0 22 * * SAT-SUN').daysOfWeek,
      equals({DateTime.saturday, DateTime.sunday}),
    );
    expect(
      next('0 22 * * SAT-MON', startAt: "2022-11-27 23:00"),
      equals('2022-11-28 22:00'),
    );
```

I'll work around this for now by using SAT,SUN instead of SAT-SUN.

Cheers!

**Comment by karbunkul** [comment]
Thanks for feedback, expression 0 22 * * SAT-MON (https://crontab.guru/#0_22_*_*_SAT-MON) is not valid cron time. Another cases added to tests, and fixed in 0.9.2.
